# Generated by Django 3.0.7 on 2020-10-18 12:56

from django.db import migrations
from django.db.models import F


def calculate_order_items_prices(apps, schema_editor):
    OrderItem = apps.get_model('foodcartapp', 'OrderItem')
    for item in OrderItem.objects.all().iterator():
        item.update(item.quantity * item.product.price)


class Migration(migrations.Migration):
    dependencies = [
        ('foodcartapp', '0039_auto_20201018_1214'),
    ]

    operations = [
        migrations.RunPython(calculate_order_items_prices)
    ]
