# Generated by Django 3.0.7 on 2020-11-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0040_auto_20201018_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Необработанный'), (1, 'Готовится'), (2, 'На доставке'), (3, 'Доставлен')], default=0, verbose_name='Статус'),
        ),
    ]
