# Generated by Django 3.0.7 on 2021-02-05 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_payment_form'),
        ('foodcartapp', '0037_auto_20210125_1833'),
    ]

    operations = [
    ]
