# Generated by Django 3.0.7 on 2021-02-05 18:47

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_merge_20210205_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='formatted_phonenumber',
            field=phonenumber_field.modelfields.PhoneNumberField(default='', max_length=128, region=None, verbose_name='номер телефона'),
            preserve_default=False,
        ),
    ]
