# Generated by Django 3.0.7 on 2021-02-05 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0048_auto_20210205_1847'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='phonenumber',
            new_name='original_phonenumber',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='formatted_phonenumber',
            new_name='phonenumber',
        ),
    ]
